#!/usr/bin/env bash
# Prints information about domains and subdomains

parse_domain () {
    entry=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $entry" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'    
}

if [ "$#" == 1 ]
then
  parse_domain "$1" "www"
  parse_domain "$1" "web-01"
  parse_domain "$1" "web-02"
  parse_domain "$1" "lb-01"
elif [ "$#" == 2 ]
then
  parse_domain "$1" "$2"
fi
