#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
redirection="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
sudo sed -i "53i $redirection" /etc/nginx/sites-available/default
service nginx restart
