#!/usr/bin/env bash
# Install nginx and redirect with 301
sudo apt-get update -y
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
redirection="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $redirection" /etc/nginx/sites-available/default
service nginx restart
