#!/usr/bin/env bash
# Install nginx. Add not found and redirect routes. Return custom header.
sudo apt-get update -y
sudo apt-get install -y nginx
echo 'Hello World!' > index.html
sudo mv index.html /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
redirection="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
notfound="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
header_val="\\\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
sudo sed -i "53i $redirection" /etc/nginx/sites-available/default
sudo sed -i "53i $notfound" /etc/nginx/sites-available/default
sudo sed -i "63i $header_val" /etc/nginx/nginx.conf
sudo service nginx restart
