#!/usr/bin/env bash
#Infinite print but listen for sigterm

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

echo "$$" > /var/run/myscript.pid
while ((1 == 1))
do echo "To infinity and beyond"
sleep 2
done
