#!/usr/bin/env bash
# Change the local host address to 127.0.0.2 and FB to 8.8.8.8
cp /etc/hosts ~/hosts.tmp
echo "127.0.0.2		localhost" > ~/hosts.tmp
echo "8.8.8.8		facebook.com" >> ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
